<a href="https://colab.research.google.com/github/Mayureshnema04/Mayuresh-Nema/blob/main/Sevanth_Session_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#Logitstic Regression
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

In [6]:
# Studying less than 3 hours chance are to fail
X = np.array([[1],[2],[3],[4],[5],[6],[7]])
y = np.array([0,0,0,1,1,1,1])

In [7]:
model = LogisticRegression()

In [9]:
model.fit(X,y)

LogisticRegression()

In [10]:
model.predict([[5]])

array([1])

In [11]:
model.predict([[10]])

array([1])

In [12]:
model.predict_proba([[5]])

array([[0.14919774, 0.85080226]])

In [14]:
model.predict_proba([[1]])

array([[0.94505985, 0.05494015]])

In [15]:
model.predict_proba([[2]])

array([[0.84534214, 0.15465786]])

In [16]:
X_test = np.array([[2],[3],[4],[6],[8]])

In [17]:
model.predict(X_test)

array([0, 0, 1, 1, 1])

In [18]:
model.predict_proba(X_test)

array([[0.84534214, 0.15465786],
       [0.6346107 , 0.3653893 ],
       [0.35561919, 0.64438081],
       [0.0527807 , 0.9472193 ],
       [0.00559461, 0.99440539]])

In [19]:
model.predict_proba([[0]])

array([[0.98186271, 0.01813729]])

In [20]:
def predict_pass(hours):
  prediction = model.predict([[hours]])

  return prediction

In [21]:
predict_pass(5)

array([1])

In [22]:
predict_pass(5)[0]

np.int64(1)

In [29]:
if predict_pass(5)[0] == 1:
  print("Student has passed the exam")
else:
    print("Student has failed the exam")

Student has passed the exam


In [32]:
predict_pass(10)

array([1])

In [33]:
a = model.predict([[5]])

In [34]:
a

array([1])

In [35]:
if a == 1:
  print("pass")

pass


In [36]:
b = model.predict(X_test)

In [37]:
b

array([0, 0, 1, 1, 1])

In [38]:
b[0]

np.int64(0)

In [39]:
b[1]

np.int64(0)

In [40]:
b[2]

np.int64(1)